export const SET_SESSION = 'SET_SESSION';
export const SET_USER = 'SET_USER';

export const MERGE_FOLLOWINGS = 'MERGE_FOLLOWINGS';

export const MERGE_ACTIVITIES = 'MERGE_ACTIVITIES';
export const SET_ACTIVITIES_NEXT_HREF = 'SET_ACTIVITIES_NEXT_HREF';
export const SET_ACTIVITIES_REQUEST_IN_RPOCESS = 'SET_ACTIVITIES_REQUEST_IN_RPOCESS';

export const SET_ACTIVE_TRACK = 'SET_ACTIVE_TRACK';
export const RESET_ACTIVE_TRACK = 'RESET_ACTIVE_TRACK';
export const SET_IS_PLAYING = 'SET_IS_PLAYING';
export const SET_TRACK_IN_PLAYLIST = 'SET_TRACK_IN_PLAYLIST';
export const REMOVE_TRACK_FROM_PLAYLIST = 'REMOVE_TRACK_FROM_PLAYLIST';

export const SET_IS_OPEN_PLAYLIST = 'SET_IS_OPEN_PLAYLIST';