export const SET_SESSION = 'SET_SESSION';
export const SET_USER = 'SET_USER';

export const SET_FOLLOWINGS = 'SET_FOLLOWINGS';
export const MERGE_FOLLOWINGS = 'MERGE_FOLLOWINGS';

export const SET_FOLLOWERS = 'SET_FOLLOWERS';
export const MERGE_ACTIVITIES = 'MERGE_ACTIVITIES';

export const SET_FAVORITES = 'SET_FAVORITES';
export const MERGE_FOLLOWERS = 'MERGE_FOLLOWERS';

export const SET_ACTIVITES = 'SET_ACTIVITES';
export const MERGE_FAVORITES = 'MERGE_FAVORITES';

export const SET_ACTIVE_TRACK = 'SET_ACTIVE_TRACK';
export const RESET_ACTIVE_TRACK = 'RESET_ACTIVE_TRACK';

export const SET_IS_PLAYING = 'SET_IS_PLAYING';

export const SET_TRACK_IN_PLAYLIST = 'SET_TRACK_IN_PLAYLIST';
export const REMOVE_TRACK_FROM_PLAYLIST = 'REMOVE_TRACK_FROM_PLAYLIST';

export const SET_IS_OPEN_PLAYLIST = 'SET_IS_OPEN_PLAYLIST';

export const MERGE_GENRE_ACTIVITIES = 'MERGE_GENRE_ACTIVITIES';

export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';

export const SET_REQUEST_IN_PROCESS = 'SET_REQUEST_IN_PROCESS';
export const SET_PAGINATE_LINK = 'SET_PAGINATE_LINK';