export const SET_SESSION = 'SET_SESSION';
export const SET_USER = 'SET_USER';

export const MERGE_FOLLOWINGS = 'MERGE_FOLLOWINGS';

export const MERGE_ACTIVITIES = 'MERGE_ACTIVITIES';
export const SET_ACTIVITIES_NEXT_HREF = 'SET_ACTIVITIES_NEXT_HREF';
export const SET_ACTIVITIES_REQUEST_IN_RPOCESS = 'SET_ACTIVITIES_REQUEST_IN_RPOCESS';